export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_FETCHING = 'REGISTER_FETCHING'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_FETCHING = 'LOGIN_FETCHING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const RELOGIN_REQUEST = 'RELOGIN_REQUEST'
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'


export const STOCK_LIST_REQUEST = 'STOCK_LIST_REQUEST'
export const STOCK_LIST_FETCHING = 'STOCK_LIST_FETCHING'
export const STOCK_LIST_FAILED = 'STOCK_LIST_FAILED'
export const STOCK_LIST_SUCCESS = 'STOCK_LIST_SUCCESS'