export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_FETCHING = 'REGISTER_FETCHING'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_FETCHING = 'LOGIN_FETCHING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const RELOGIN_REQUEST = 'RELOGIN_REQUEST'
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'


export const STOCK_LIST_REQUEST = 'STOCK_LIST_REQUEST'
export const STOCK_LIST_FETCHING = 'STOCK_LIST_FETCHING'
export const STOCK_LIST_FAILED = 'STOCK_LIST_FAILED'
export const STOCK_LIST_SUCCESS = 'STOCK_LIST_SUCCESS'


export const STOCK_CREATE_REQUEST = 'STOCK_CREATE_REQUEST'
export const STOCK_CREATE_FETCHING = 'STOCK_CREATE_FETCHING'
export const STOCK_CREATE_FAILED = 'STOCK_CREATE_FAILED'
export const STOCK_CREATE_SUCCESS = 'STOCK_CREATE_SUCCESS'

export const STOCK_EDIT_REQUEST = 'STOCK_EDIT_REQUEST'
export const STOCK_EDIT_FETCHING = 'STOCK_EDIT_FETCHING'
export const STOCK_EDIT_FAILED = 'STOCK_EDIT_FAILED'
export const STOCK_EDIT_SUCCESS = 'STOCK_EDIT_SUCCESS'


export const STOCK_DELETE_REQUEST = 'STOCK_DELETE_REQUEST'
export const STOCK_DELETE_FETCHING = 'STOCK_DELETE_FETCHING'
export const STOCK_DELETE_FAILED = 'STOCK_DELETE_FAILED'
export const STOCK_DELETE_SUCCESS = 'STOCK_DELETE_SUCCESS'

export const STOCK_GET_BY_ID_REQUEST = 'STOCK_GET_BY_ID_REQUEST'
export const STOCK_GET_BY_ID_FETCHING = 'STOCK_GET_BY_ID_FETCHING'
export const STOCK_GET_BY_ID_FAILED = 'STOCK_GET_BY_ID_FAILED'
export const STOCK_GET_BY_ID_SUCCESS = 'STOCK_GET_BY_ID_SUCCESS'